# Generated by Django 3.2.3 on 2021-06-06 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('empleado', '0001_initial'),
        ('menu', '0002_auto_20210605_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_comanda', models.DateField(auto_now_add=True, verbose_name='fecha comanda')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='total')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado', verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'detalle de comanda',
                'verbose_name_plural': 'detalles de comandas',
                'db_table': 'comanda_detalle',
            },
        ),
        migrations.CreateModel(
            name='DetalleComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='sub_total')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu', verbose_name='Menu')),
            ],
        ),
    ]
