# Generated by Django 3.2.3 on 2021-06-06 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comanda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comanda',
            options={'verbose_name': 'comanda', 'verbose_name_plural': 'Comandas'},
        ),
        migrations.AddField(
            model_name='detallecomanda',
            name='comandas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comanda.comanda', verbose_name='comanda'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='comanda',
            table='comanda',
        ),
    ]
