# Generated by Django 3.2.3 on 2021-06-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comanda', '0002_auto_20210605_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comanda',
            options={'verbose_name': 'Comanda', 'verbose_name_plural': 'comandas'},
        ),
        migrations.RenameField(
            model_name='detallecomanda',
            old_name='comandas',
            new_name='comanda',
        ),
    ]
