# Generated by Django 3.2.3 on 2021-06-05 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombres')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellidos')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha nacimiento')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('direccion', models.CharField(blank=True, max_length=50, null=True, verbose_name='direccion')),
                ('sueldo', models.CharField(blank=True, max_length=14, null=True, verbose_name='sueldo')),
                ('dpi', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='dpi')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='solo incluir numeros', verbose_name='numero de Telefono')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado', verbose_name='Empleado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TelEmpleado', to='comun.tipotelefono', verbose_name='Tipo Telefono')),
            ],
            options={
                'verbose_name': 'Telefono de Empleado',
                'verbose_name_plural': 'Telefonos de Empleado',
            },
        ),
    ]
