# Generated by Django 3.2.3 on 2021-06-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='platillo',
        ),
        migrations.AddField(
            model_name='menu',
            name='descripcion',
            field=models.CharField(default=1, max_length=50, verbose_name='descripcion'),
            preserve_default=False,
        ),
    ]
